version: "3"
services:
  api:
    build: .
    depends_on:
      - elasticsearch
    volumes:
      - ./src/index.ts:/usr/src/app/index.ts
      - ./src/package.json:/usr/src/app/package.json
      - ./src/cmd:/usr/src/app/cmd
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 3000:3000
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.8.5
    ports:
      - 5601:5601
    environment:
      - elasticsearch.hosts='["http://elasticsearch:9200"]'
